---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify
  hosts: instance
  gather_facts: false # Quicker, if you do not need facts
  tasks:
    - name: Assert something
      ansible.builtin.assert:
        that: true
    - name: Check for vector config file
      ansible.builtin.stat:
        path: /etc/vector/vector.yaml
      register: vector_config_file
    - name: Assert vector config exists
      ansible.builtin.assert:
        that: 
          - "vector_config_file.stat.exists"
